### PR TITLE
update from pc37utn including new utk_digital_base box

### PR DESCRIPTION
**Pull request by pc37utn**

### CODE REVIEW

**Comment by pc37utn** [comment]
re-opened this pr because php version changes were in base box

**Comment by CanOfBees** [comment]
@pc37utn taking a look at this now.

**Review by cdeaneGit — COMMENTED** [review]
@pc37utn  Looking now.

**Review by CanOfBees — APPROVED** [review]
The base box comes up and access works at `localhost:8000`. Looks good!

**Comment by cdeaneGit** [comment]
This is working perfectly except for one very small problem that I was able to demonstrate to Paul and he knows how to adjust.
I approve this code for merge.

**Pull request merged**
